config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'homepage#welcome'
get'/about', to: 'pages#about'
get'/signup', to: 'users#new'
resources :articles


# post 'users', to: 'users#create'



resources :users, except: [:new]
get 'login' ,to: 'sessions#new'
post 'login' ,to: 'sessions#create'
delete'logout' ,to: 'sessions#destroy'


resources :categories, except: [:destroy]
end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories,  through: :article_categories
  validates :title, presence: true , length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
  validates :user_id ,presence: true
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
 class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name , presence: true

 end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  before_save{ self.email = email.downcase}
  validates :username, presence: true,
             uniqueness: {case_sensitive: false},
             length: {minimum:3,  maximum:25}
VALID_EMAIL_REGEX =  /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
             validates :email, presence: true,length: {maximum:105},
             uniqueness: {case_sensitive: false},
             format: {with: VALID_EMAIL_REGEX} 
             
  has_secure_password
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
   @current_user ||=  User.find(session[:user_id]) if session[:user_id]
  end


  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger]= "you must be logged in to perform that action"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
 

  def index
    @articles =Article.paginate(page: params[:page], per_page: 5)
  end
  def new  

    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = User.first
    if @article.save
      flash[:success] ="article is successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
 
  end

  def show
    @article =Article.find(params[:id])
  end  
  def edit
    @article =Article.find(params[:id])
  end
  def update
    @article =Article.find(params[:id])
    if @article.update(article_params)
      flash[:success] ="article is successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end

  end
  def destroy
    @article =Article.find(params[:id])
    @article.destroy
    flash[:danger] = "article was successfully deleted"
    redirect_to articles_path
  end

private
  def article_params
    params.require(:article).permit(:title,:description, category_ids:[]) 
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
  end
  def new
  end
  def show
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def welcome
    redirect_to articles_path if logged_in?
  end
end

app/controllers/pages_controller.rb
 class PagesController < ApplicationController
  def about


  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new


  end


  def create
 
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
     session[:user_id] = user.id
     flash[:success]= "you have succesfully login"
     redirect_to user_path(user)
    else
     flash.now[:danger] = "there is something wrong with your log in details"
     render 'new'
    end
  end

  def destroy
 session[:user_id] = nil
 flash[:success]= "you have succesfully logout"
 redirect_to root_path
  end
end
 

app/controllers/users_controller.rb
class UsersController < ApplicationController
 def index
  @users =User.paginate(page: params[:page], per_page: 5)
 end

  def new
    @user =User.new
  end


  def create
       @user = User.create(user_params)
       if @user.save
      flash[:success] ="welcome to the alphablog "
      redirect_to articles_path
    else
      render 'new'
    end
  end


def edit
  @user =User.find(params[:id])
end


def update
   @user =User.find(params[:id])
    if @user.update(user_params)
      flash[:success] ="your account was updates successfully"
      redirect_to articles_path
    else
      render 'edit'
    end
  end


  def show
   @user =User.find(params[:id])
 end

  private 
  def user_params
    params.require(:user).permit(:username,:email,:password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user)
     gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
     gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
     image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end
end
 

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/articles/_article.html.erb
<% object.each do |article|%>
  <div class ="row">
    <div class ="col-xs-8 col-xs-offset-2">
      <div class ="well well-lg">
        <div class ="article-title">
  
    <%=link_to article.title, article_path(article)%>
  </div>
  <div class= "article.body">
    <%=truncate(article.description, length: 100)%>
    <div class ="article-meta-details">
    <small> Created by: <%=article.user.username if article.user%>
                        <%=time_ago_in_words(article.created_at)%>ago ,
                        last_updated: <%=time_ago_in_words(article.updated_at)%> ago
     </small>
   </div>
  </div>
  <%if logged_in? && current_user == article.user%>
    <div class="article-action"> 
    <%=link_to'Edit article', edit_article_path(article), class: "btn btn-xs btn-primary"%>
    <%=link_to'delete this article', article_path(article), method: :delete, 
                                   data: {confirm: 'are you sure you want to delete this article?'}, class: "btn btn-xs btn-danger"%>
</div>
<%end%>
</div>
</div>
</div>
  <%end%>
 

app/views/articles/_form.html.erb
<%=render partial: 'shared/errors',locals: {object: @article}%>

<div class ='row'>
	<div class= col-xs-12>
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
		<div class="form-group">
		  <div class="control-label col-sm-2 ">
		    <%=f.label :Title%> 
		  </div>
			<div class= "col-sm-10">
			  <%= f.text_field :title, class: "form-control", placeholder: "tiltle of article", autofocus:  true%>
			</div>
		</div>


		<div class = "form-group">
			<div class = "control-label col-sm-2">
		  <%=f.label :Description%>
		</div>
		<div class= "col-sm-10">
		<%= f.text_area :description,rows: 10, class: "form-control", placeholder: "Description of article", autofocus:  true %>
		  </div>

		  <div class = "form-group">
		  	<div class ="row">
		 	<div class = "col-sm-8">
		  <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
          <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox")+ cb.text} %>
		  <%end%>
		</div>  
		</div>


		 <div class = "form-group">
		 	<div class = "col-sm-10">
		  <%= f.submit class: 'btn btn-primary btn-lg' %>
		</div>
		</div>
		<% end %>
		<div class= "col-xs-4 col-xs-offset-4">
		[ <%=link_to 'cancel request and return to article listing', articles_path%>]
		</div>
		</div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 align ="center ">edit existing article</h1>

<%=render 'form'%>

app/views/articles/index.html.erb
<h1 align ="center">listing all articles</h1>
<div align= "center">
  <%= will_paginate%>
</div>
<%=render partial: 'article', locals: {object: @articles} %>

<div align= "center">
  <%= will_paginate%>
</div>





 

app/views/articles/new.html.erb
<h1 align="center">create an article</h1>

<%=render partial: 'form', local: {object: @user}%>

app/views/articles/show.html.erb
<h2 align ="center">
 Title:  <%=@article.title%>
</h2>

<div class= "well col-xs-8 col-xs-offset-2">
   <%if @article.user%>

	<ul class = "listing">
	<div class = "row center">
		<div class = "col-md-4 col-md-offset-4">
			<li>created by: </li>
			<li><%= link_to gravatar_for(@article. user), user_path(@article.user)%></li>
			<li class= "article-title">
				<%= link_to@article.user.username, user_path(@article.user)%>
			</li>
			<li>
				<small>
				 <%= pluralize(@article.user.articles.count, "article") if @article.user.articles %>
				</small>
			</li>
		</div>
	</div>
</ul>
<%end%>
  <h4 class ="center"><strong>Description</strong></h4>
  <hr>
  <%= simple_format(@article.description)%>
  <div class="article-action">
  	<% if logged_in? && current_user == @article.user%>
    <%=link_to'Edit article', edit_article_path(@article), class: "btn btn-xs btn-primary"%>
    <%=link_to'delete this article', article_path(@article), method: :delete, 
                                   data: {confirm: 'are you sure you want to delete this article?'}, class: "btn btn-xs btn-danger"%>
                                   <%end %>
    <%=link_to'View all articles', articles_path, class: "btn btn-xs btn-success"%>
</div>
</div>




  

app/views/categories/index.html.erb
index.html.erb

app/views/categories/new.html.erb
new.html.erb

app/views/categories/show.html.erb
show.html.erb

app/views/homepage/welcome.html.erb
<div class="centre jumbotron">
  <h1>ALPHA BLOG!</h1>
 
  <%=link_to 'Sign up now', signup_path, class: "btn btn-primary btn-lg btn-xlarge" %>
</div>

app/views/layouts/_footer.html.erb
<div class ="container">
	<footer class= footer>
		<small>
			copyright &copy; <a href="https://google.com">complete ruby on rails developer</a>
			by <a href="https://www.facebook.com/kartikey.soni.50">Kartikey soni</a>
		</small>
		<nav>
		<ul>
			<li>
				<%=link_to "about", about_path%>
			</li>
		</ul>
			</nav>
	</footer>
</div>

app/views/layouts/_header.html.erb
 <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%=link_to "ALPHA BLOG",root_path, class: "navbar-brand", id: "logo" %>
       <%=link_to "New Article",new_article_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <li><%=link_to 'ARTICLES',articles_path%></li>
        <li><%=link_to 'Users',users_path%></li>
           <%if logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%=link_to 'new article',new_article_path%></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
            <%end%>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <%if logged_in?%>
        <li><%=link_to 'Log Out',logout_path, method: :delete%></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%=link_to 'Edit your Profile', edit_user_path(current_user)%></li>
            <li><%=link_to 'View your Profile', user_path(current_user)%></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
        <%else%>
        <li><%=link_to 'Log in',login_path%></li>
        <li><%=link_to 'Sign up',signup_path%></li>
        <%end%>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_message.html.erb
<div class="row">
	<div class= "col-xs-10 col-xs-offset-1">
< %flash.each do |name,msg| %>
<div class= 'alert alert-<%="#{name}"%>'
	<a href="#" class= "close" data-dismiss= "alert">&#215;</a>
	<%=content_tag :div, msg :id => "flash_#{name}" if msg.is_a?(string)%>
</div>
<ul>
	<li><%= msg%></li>
</ul>
<%end%>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">
  </head>

  <body>
  	<%=render 'layouts/header'%>
    <div class="container">      
    
    <%= yield %>
    </div>

<%=render 'layouts/footer'%>


  </body>
</html>

app/views/pages/about.html.erb
<h1>this is th description of our blogs</h1>

<%=link_to 'home',root_path %>

app/views/shared/_errors.html.erb
<%if object.errors.any?%>
<div class= "row">
  <div class= "col-xs-8 col-xs-offset-2">
    <div class= "panel panel-danger">
      <div class= "panel panel-heading">
        <h2 class= "panel-title">
          <%= pluralize(object.errors.count, "error")%>
          prohibite thisarticle from being saved:
        </h2>
        <div class ="panel-body">
          <ul>
            <% object.errors.full_messages.each do |msg|%>
            <li><%=msg%></li>
            <%end%>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>


<%end%>

app/views/users/_form.html.erb
<%= render partial: 'shared/errors', locals: {object: @user}%>
<div class ='row'>
	<div class= col-xs-12>
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
		<div class="form-group">
		  <div class="control-label col-sm-2 ">
		    <%=f.label :Username%> 
		  </div>
			<div class= "col-sm-8">
			  <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus:  true%>
			</div>
		</div>


		<div class = "form-group">
			<div class = "control-label col-sm-2">
		  <%=f.label :email%>
		</div>
		<div class= "col-sm-8">
		<%= f.email_field :email, class: "form-control", placeholder: "email", autofocus:  true %>
		  </div>
		</div>

		  		
		  		<div class = "form-group">
			<div class = "control-label col-sm-2">
		  <%=f.label :password%>
		</div>
		<div class= "col-sm-8">
		<%= f.password_field :password, class: "form-control", placeholder: "enter password"%>
		  </div>
		</div>
		 <div class = "form-group">
		 	<div class = "col-sm-offset-2 col-sm-10">
		  <%= f.submit "SignUp", class: 'btn btn-primary btn-lg' %>
		</div>
		</div>
		<% end %>
		<div class= "col-xs-4 col-xs-offset-4">
		[ <%=link_to 'cancel request and return to article listing', articles_path%>]
		</div>
		</div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit your account</h1>
<%= render partial: 'shared/errors', locals: {object: @user}%>
<div class ='row'>
	<div class= col-xs-12>
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
		<div class="form-group">
		  <div class="control-label col-sm-2 ">
		    <%=f.label :Username%> 
		  </div>
			<div class= "col-sm-8">
			  <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus:  true%>
			</div>
		</div>


		<div class = "form-group">
			<div class = "control-label col-sm-2">
		  <%=f.label :email%>
		</div>
		<div class= "col-sm-8">
		<%= f.email_field :email, class: "form-control", placeholder: "email", autofocus:  true %>
		  </div>
		</div>

		  		
		  		<div class = "form-group">
			<div class = "control-label col-sm-2">
		  <%=f.label :password%>
		</div>
		<div class= "col-sm-8">
		<%= f.password_field :password, class: "form-control", placeholder: "enter password"%>
		  </div>
		</div>
		 <div class = "form-group">
		 	<div class = "col-sm-offset-2 col-sm-10">
		  <%= f.submit "SignUp", class: 'btn btn-primary btn-lg' %>
		</div>
		</div>
		<% end %>
		<div class= "col-xs-4 col-xs-offset-4">
		[ <%=link_to 'cancel request and return to article listing', articles_path%>]
		</div>
		</div>
  </div>
</div>

app/views/users/index.html.erb
<h1 align = "center"> All Alpha blog </h1>
<div align ="center">
	  <%= will_paginate%>
<% @users.each do |user|%>
<ul class = "listing">
	<div class = "row">
		<div class = "well col-md-4 col-md-offset-4">
			<li><%= link_to gravatar_for(user), user_path(user)%></li>
			<li class= "article-title">
				<%= link_to user.username, user_path(user)%>
			</li>
			<li>
				<small>
					<%= pluralize(user.articles.count, "article") if user.articles %>
				</small>
			</li>
		</div>
	</div>
</ul>
<%end%>
  <%= will_paginate%>

app/views/users/new.html.erb
<h1 align ="center">Signup for alpha blog</h1>
<%= render partial: 'shared/errors', locals: {object: @user}%>
<div class ='row'>
	<div class= col-xs-12>
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
		<div class="form-group">
		  <div class="control-label col-sm-2 ">
		    <%=f.label :Username%> 
		  </div>
			<div class= "col-sm-8">
			  <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus:  true%>
			</div>
		</div>


		<div class = "form-group">
			<div class = "control-label col-sm-2">
		  <%=f.label :email%>
		</div>
		<div class= "col-sm-8">
		<%= f.email_field :email, class: "form-control", placeholder: "email", autofocus:  true %>
		  </div>
		</div>

		  		
		  		<div class = "form-group">
			<div class = "control-label col-sm-2">
		  <%=f.label :password%>
		</div>
		<div class= "col-sm-8">
		<%= f.password_field :password, class: "form-control", placeholder: "enter password"%>
		  </div>
		</div>
		 <div class = "form-group">
		 	<div class = "col-sm-offset-2 col-sm-10">
		  <%= f.submit "SignUp", class: 'btn btn-primary btn-lg' %>
		</div>
		</div>
		<% end %>
		<div class= "col-xs-4 col-xs-offset-4">
		[ <%=link_to 'cancel request and return to article listing', articles_path%>]
		</div>
		</div>
  </div>
</div>

app/views/users/show.html.erb
<h1 align= "center">welcome to the page</h1>
<div class ="row">
  <div class= "col md-2 col-md-offset-6 center">
<%= gravatar_for @user %>
  </div>
</div>
<h4 align ="center"><%=@user.username%>'s articles</h4>

<%=render 'articles/article', object:  @user.articles%>